/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'tutor-profiles': TutorProfile;
    subjects: Subject;
    reviews: Review;
    wallets: Wallet;
    transactions: Transaction;
    bookings: Booking;
    students: Student;
    classes: Class;
    'class-invitations': ClassInvitation;
    whiteboards: Whiteboard;
    'whiteboard-slides': WhiteboardSlide;
    'live-sessions': LiveSession;
    attendance: Attendance;
    'live-session-participants': LiveSessionParticipant;
    assessments: Assessment;
    'assessment-questions': AssessmentQuestion;
    'tutor-assessments': TutorAssessment;
    'assessment-results': AssessmentResult;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'tutor-profiles': TutorProfilesSelect<false> | TutorProfilesSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    'class-invitations': ClassInvitationsSelect<false> | ClassInvitationsSelect<true>;
    whiteboards: WhiteboardsSelect<false> | WhiteboardsSelect<true>;
    'whiteboard-slides': WhiteboardSlidesSelect<false> | WhiteboardSlidesSelect<true>;
    'live-sessions': LiveSessionsSelect<false> | LiveSessionsSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'live-session-participants': LiveSessionParticipantsSelect<false> | LiveSessionParticipantsSelect<true>;
    assessments: AssessmentsSelect<false> | AssessmentsSelect<true>;
    'assessment-questions': AssessmentQuestionsSelect<false> | AssessmentQuestionsSelect<true>;
    'tutor-assessments': TutorAssessmentsSelect<false> | TutorAssessmentsSelect<true>;
    'assessment-results': AssessmentResultsSelect<false> | AssessmentResultsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  accountType: 'admin' | 'tutor' | 'parent' | 'student';
  phoneNumber: string;
  country?: string | null;
  timezone?: string | null;
  avatar?: (string | null) | Media;
  /**
   * For child/student accounts created by a parent.
   */
  parent?: (string | null) | User;
  /**
   * True for child accounts created by a parent (auto-generated email and password).
   */
  isManagedAccount?: boolean | null;
  hasCompletedOnboarding?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-profiles".
 */
export interface TutorProfile {
  id: string;
  /**
   * Auto-generated unique slug for the tutor profile.
   */
  slug: string;
  user: string | User;
  /**
   * Check to approve this tutor profile.
   */
  isApproved?: boolean | null;
  /**
   * Average rating for this tutor (0-5).
   */
  rating?: number | null;
  /**
   * Total number of reviews received by this tutor.
   */
  totalReviews?: number | null;
  /**
   * Whether the tutor has completed the onboarding flow.
   */
  onboardingCompleted?: boolean | null;
  /**
   * A short headline or tagline for the tutor profile.
   */
  headline?: string | null;
  bio?: string | null;
  yearsOfExperience?: number | null;
  mode?: ('online' | 'hybrid') | null;
  /**
   * How the tutor plans to use TutorCourt.
   */
  usagePlan?: ('existing' | 'marketplace' | 'both') | null;
  /**
   * Subjects this tutor teaches.
   */
  subjects?: (string | Subject)[] | null;
  /**
   * Hourly rate in Naira.
   */
  hourlyRate?: number | null;
  /**
   * Types of classes standardly offered by this tutor.
   */
  type?: ('one-on-one' | 'group')[] | null;
  /**
   * Minimum age of students the tutor teaches.
   */
  minAge?: number | null;
  /**
   * Maximum age of students the tutor teaches.
   */
  maxAge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  review: string;
  rating: number;
  user: string | User;
  tutor: string | TutorProfile;
  tutorResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: string;
  user: string | User;
  currency: 'ngn' | 'usd';
  balance: number;
  creditBalance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  sender: string | User;
  receiver: string | User;
  tutor?: (string | null) | User;
  amount: number;
  currency: 'usd' | 'ngn';
  status: 'paid' | 'pending';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  tutor: string | TutorProfile;
  student: string | User;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  /**
   * Start date of the engagement
   */
  date: string;
  /**
   * End date of the engagement
   */
  endDate: string;
  hoursPerDay: number;
  daysOfWeek: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  subjects: {
    subject: string;
    id?: string | null;
  }[];
  /**
   * Total price for this booking
   */
  price: number;
  /**
   * Message from the student to the tutor
   */
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: string;
  user: string | User;
  parent: string | User;
  firstName: string;
  lastName: string;
  generatedEmail: string;
  generatedPassword: string;
  gradeLevel?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: string;
  tutor: string | User;
  title?: string | null;
  subject: string | Subject;
  description?: string | null;
  classType: 'one-on-one' | 'group';
  maxStudents?: number | null;
  startDate: string;
  endDate: string;
  schedule: {
    day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
    startTime: string;
    endTime: string;
    id?: string | null;
  }[];
  students?: (string | User)[] | null;
  parents?: (string | User)[] | null;
  status: 'scheduled' | 'active' | 'completed' | 'cancelled';
  whiteboard?: (string | null) | Whiteboard;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards".
 */
export interface Whiteboard {
  id: string;
  title: string;
  owner: string | User;
  class?: (string | null) | Class;
  liveSession?: (string | null) | LiveSession;
  shareToken?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-sessions".
 */
export interface LiveSession {
  id: string;
  class: string | Class;
  tutor: string | User;
  roomId: string;
  scheduledFor?: string | null;
  startedAt?: string | null;
  endedAt?: string | null;
  status: 'scheduled' | 'waiting' | 'live' | 'ended' | 'cancelled';
  attendees?: (string | User)[] | null;
  showWhiteboard?: boolean | null;
  activeWhiteboard?: (string | null) | Whiteboard;
  coinsConsumed?: number | null;
  durationMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-invitations".
 */
export interface ClassInvitation {
  id: string;
  class: string | Class;
  inviter: string | User;
  inviteeEmail: string;
  inviteeType: 'parent' | 'student';
  token: string;
  status: 'pending' | 'accepted' | 'declined' | 'expired';
  acceptedBy?: (string | null) | User;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboard-slides".
 */
export interface WhiteboardSlide {
  id: string;
  whiteboard: string | Whiteboard;
  order: number;
  title?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  thumbnail?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: string;
  liveSession: string | LiveSession;
  class: string | Class;
  student: string | User;
  parent?: (string | null) | User;
  tutor?: (string | null) | User;
  joinedAt: string;
  leftAt?: string | null;
  durationMinutes?: number | null;
  status: 'present' | 'late' | 'left-early' | 'absent';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-participants".
 */
export interface LiveSessionParticipant {
  id: string;
  liveSession: string | LiveSession;
  class: string | Class;
  user: string | User;
  accountType: 'tutor' | 'student' | 'parent';
  joinedAt: string;
  leftAt?: string | null;
  durationSeconds?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments".
 */
export interface Assessment {
  id: string;
  title: string;
  description?: string | null;
  subject: string | Subject;
  tutor: string | User;
  type: 'quiz' | 'flashcard' | 'practice_test' | 'homework';
  /**
   * Optional time limit in minutes (0 = no limit)
   */
  timeLimitMinutes?: number | null;
  /**
   * Max questions (up to 100)
   */
  maxQuestions?: number | null;
  /**
   * Passing score percentage (0-100)
   */
  passingScore?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-questions".
 */
export interface AssessmentQuestion {
  id: string;
  assessment: string | Assessment;
  /**
   * Supports Markdown syntax
   */
  questionText: string;
  type: 'single_choice' | 'multiple_choice' | 'true_false';
  /**
   * For choice-based questions. Mark one or more as correct.
   */
  options?:
    | {
        optionText: string;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown after the student answers (optional)
   */
  explanation?: string | null;
  points: number;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-assessments".
 */
export interface TutorAssessment {
  id: string;
  assessment: string | Assessment;
  tutor: string | User;
  student: string | User;
  class: string | Class;
  selectedQuestions?: (string | AssessmentQuestion)[] | null;
  status: 'pending' | 'in_progress' | 'completed' | 'expired';
  dueDate?: string | null;
  instructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-results".
 */
export interface AssessmentResult {
  id: string;
  tutorAssessment: string | TutorAssessment;
  student: string | User;
  tutor: string | User;
  answers?:
    | {
        question: string | AssessmentQuestion;
        selectedOptions?:
          | {
              optionIndex?: number | null;
              id?: string | null;
            }[]
          | null;
        textAnswer?: string | null;
        isCorrect?: boolean | null;
        pointsEarned?: number | null;
        id?: string | null;
      }[]
    | null;
  totalPoints?: number | null;
  earnedPoints?: number | null;
  /**
   * Score as a percentage (0-100)
   */
  score?: number | null;
  passed?: boolean | null;
  submittedAt?: string | null;
  timeTakenSeconds?: number | null;
  /**
   * Optional tutor feedback on the result
   */
  feedback?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  type:
    | 'student_joined_class'
    | 'parent_accepted_invite'
    | 'student_added_to_class'
    | 'assessment_completed'
    | 'assessment_sent'
    | 'new_booking'
    | 'class_reminder'
    | 'payment_received'
    | 'general';
  title: string;
  message: string;
  isRead?: boolean | null;
  /**
   * Optional URL to redirect to when notification is clicked
   */
  link?: string | null;
  relatedEntity?: {
    collection?: string | null;
    id?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tutor-profiles';
        value: string | TutorProfile;
      } | null)
    | ({
        relationTo: 'subjects';
        value: string | Subject;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'wallets';
        value: string | Wallet;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'students';
        value: string | Student;
      } | null)
    | ({
        relationTo: 'classes';
        value: string | Class;
      } | null)
    | ({
        relationTo: 'class-invitations';
        value: string | ClassInvitation;
      } | null)
    | ({
        relationTo: 'whiteboards';
        value: string | Whiteboard;
      } | null)
    | ({
        relationTo: 'whiteboard-slides';
        value: string | WhiteboardSlide;
      } | null)
    | ({
        relationTo: 'live-sessions';
        value: string | LiveSession;
      } | null)
    | ({
        relationTo: 'attendance';
        value: string | Attendance;
      } | null)
    | ({
        relationTo: 'live-session-participants';
        value: string | LiveSessionParticipant;
      } | null)
    | ({
        relationTo: 'assessments';
        value: string | Assessment;
      } | null)
    | ({
        relationTo: 'assessment-questions';
        value: string | AssessmentQuestion;
      } | null)
    | ({
        relationTo: 'tutor-assessments';
        value: string | TutorAssessment;
      } | null)
    | ({
        relationTo: 'assessment-results';
        value: string | AssessmentResult;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  accountType?: T;
  phoneNumber?: T;
  country?: T;
  timezone?: T;
  avatar?: T;
  parent?: T;
  isManagedAccount?: T;
  hasCompletedOnboarding?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-profiles_select".
 */
export interface TutorProfilesSelect<T extends boolean = true> {
  slug?: T;
  user?: T;
  isApproved?: T;
  rating?: T;
  totalReviews?: T;
  onboardingCompleted?: T;
  headline?: T;
  bio?: T;
  yearsOfExperience?: T;
  mode?: T;
  usagePlan?: T;
  subjects?: T;
  hourlyRate?: T;
  type?: T;
  minAge?: T;
  maxAge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  review?: T;
  rating?: T;
  user?: T;
  tutor?: T;
  tutorResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  user?: T;
  currency?: T;
  balance?: T;
  creditBalance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  sender?: T;
  receiver?: T;
  tutor?: T;
  amount?: T;
  currency?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  tutor?: T;
  student?: T;
  status?: T;
  date?: T;
  endDate?: T;
  hoursPerDay?: T;
  daysOfWeek?: T;
  subjects?:
    | T
    | {
        subject?: T;
        id?: T;
      };
  price?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  user?: T;
  parent?: T;
  firstName?: T;
  lastName?: T;
  generatedEmail?: T;
  generatedPassword?: T;
  gradeLevel?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  tutor?: T;
  title?: T;
  subject?: T;
  description?: T;
  classType?: T;
  maxStudents?: T;
  startDate?: T;
  endDate?: T;
  schedule?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  students?: T;
  parents?: T;
  status?: T;
  whiteboard?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-invitations_select".
 */
export interface ClassInvitationsSelect<T extends boolean = true> {
  class?: T;
  inviter?: T;
  inviteeEmail?: T;
  inviteeType?: T;
  token?: T;
  status?: T;
  acceptedBy?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards_select".
 */
export interface WhiteboardsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  class?: T;
  liveSession?: T;
  shareToken?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboard-slides_select".
 */
export interface WhiteboardSlidesSelect<T extends boolean = true> {
  whiteboard?: T;
  order?: T;
  title?: T;
  data?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-sessions_select".
 */
export interface LiveSessionsSelect<T extends boolean = true> {
  class?: T;
  tutor?: T;
  roomId?: T;
  scheduledFor?: T;
  startedAt?: T;
  endedAt?: T;
  status?: T;
  attendees?: T;
  showWhiteboard?: T;
  activeWhiteboard?: T;
  coinsConsumed?: T;
  durationMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  liveSession?: T;
  class?: T;
  student?: T;
  parent?: T;
  tutor?: T;
  joinedAt?: T;
  leftAt?: T;
  durationMinutes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-participants_select".
 */
export interface LiveSessionParticipantsSelect<T extends boolean = true> {
  liveSession?: T;
  class?: T;
  user?: T;
  accountType?: T;
  joinedAt?: T;
  leftAt?: T;
  durationSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments_select".
 */
export interface AssessmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  subject?: T;
  tutor?: T;
  type?: T;
  timeLimitMinutes?: T;
  maxQuestions?: T;
  passingScore?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-questions_select".
 */
export interface AssessmentQuestionsSelect<T extends boolean = true> {
  assessment?: T;
  questionText?: T;
  type?: T;
  options?:
    | T
    | {
        optionText?: T;
        isCorrect?: T;
        id?: T;
      };
  explanation?: T;
  points?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-assessments_select".
 */
export interface TutorAssessmentsSelect<T extends boolean = true> {
  assessment?: T;
  tutor?: T;
  student?: T;
  class?: T;
  selectedQuestions?: T;
  status?: T;
  dueDate?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-results_select".
 */
export interface AssessmentResultsSelect<T extends boolean = true> {
  tutorAssessment?: T;
  student?: T;
  tutor?: T;
  answers?:
    | T
    | {
        question?: T;
        selectedOptions?:
          | T
          | {
              optionIndex?: T;
              id?: T;
            };
        textAnswer?: T;
        isCorrect?: T;
        pointsEarned?: T;
        id?: T;
      };
  totalPoints?: T;
  earnedPoints?: T;
  score?: T;
  passed?: T;
  submittedAt?: T;
  timeTakenSeconds?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  link?: T;
  relatedEntity?:
    | T
    | {
        collection?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}