/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'tutor-profiles': TutorProfile;
    subjects: Subject;
    'subject-categories': SubjectCategory;
    reviews: Review;
    wallets: Wallet;
    transactions: Transaction;
    'payout-requests': PayoutRequest;
    bookings: Booking;
    students: Student;
    classes: Class;
    'class-invitations': ClassInvitation;
    whiteboards: Whiteboard;
    'whiteboard-slides': WhiteboardSlide;
    'live-sessions': LiveSession;
    attendance: Attendance;
    'live-session-participants': LiveSessionParticipant;
    'live-session-messages': LiveSessionMessage;
    assessments: Assessment;
    'assessment-questions': AssessmentQuestion;
    'tutor-assessments': TutorAssessment;
    'assessment-results': AssessmentResult;
    notifications: Notification;
    'activity-logs': ActivityLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'tutor-profiles': TutorProfilesSelect<false> | TutorProfilesSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    'subject-categories': SubjectCategoriesSelect<false> | SubjectCategoriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payout-requests': PayoutRequestsSelect<false> | PayoutRequestsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    'class-invitations': ClassInvitationsSelect<false> | ClassInvitationsSelect<true>;
    whiteboards: WhiteboardsSelect<false> | WhiteboardsSelect<true>;
    'whiteboard-slides': WhiteboardSlidesSelect<false> | WhiteboardSlidesSelect<true>;
    'live-sessions': LiveSessionsSelect<false> | LiveSessionsSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'live-session-participants': LiveSessionParticipantsSelect<false> | LiveSessionParticipantsSelect<true>;
    'live-session-messages': LiveSessionMessagesSelect<false> | LiveSessionMessagesSelect<true>;
    assessments: AssessmentsSelect<false> | AssessmentsSelect<true>;
    'assessment-questions': AssessmentQuestionsSelect<false> | AssessmentQuestionsSelect<true>;
    'tutor-assessments': TutorAssessmentsSelect<false> | TutorAssessmentsSelect<true>;
    'assessment-results': AssessmentResultsSelect<false> | AssessmentResultsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  accountType: 'admin' | 'tutor' | 'parent' | 'student';
  /**
   * Required for tutors and parents. Managed student accounts may not have one.
   */
  phoneNumber?: string | null;
  country?: string | null;
  timezone?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Date of birth. Used to determine if parental consent is required (K-12, COPPA).
   */
  dateOfBirth?: string | null;
  /**
   * Uncheck to disable account access without deleting the record.
   */
  isActive?: boolean | null;
  /**
   * For child/student accounts created by a parent.
   */
  parent?: (number | null) | User;
  /**
   * True for child accounts created by a parent (auto-generated email and password).
   */
  isManagedAccount?: boolean | null;
  /**
   * Required for students under 13 (COPPA). Set when parent registers the child.
   */
  parentalConsentGiven?: boolean | null;
  hasCompletedOnboarding?: boolean | null;
  /**
   * Subjects the student is interested in learning.
   */
  subjectsOfInterest?: (number | Subject)[] | null;
  /**
   * Current Nigerian grade level.
   */
  gradeLevel?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )
    | null;
  /**
   * What the student hopes to achieve.
   */
  learningGoals?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Auto-populated from the authenticated uploader.
   */
  uploadedBy?: (number | null) | User;
  purpose?:
    | (
        | 'avatar'
        | 'class_asset'
        | 'assessment_question'
        | 'identity_document'
        | 'certification'
        | 'class_material'
        | 'general'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: number;
  name: string;
  category: number | SubjectCategory;
  /**
   * Nigerian grade levels this subject applies to (optional filter).
   */
  gradeLevels?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-categories".
 */
export interface SubjectCategory {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-profiles".
 */
export interface TutorProfile {
  id: number;
  /**
   * Auto-generated unique slug for the tutor profile.
   */
  slug: string;
  user: number | User;
  /**
   * Check to approve this tutor profile.
   */
  isApproved?: boolean | null;
  /**
   * K-12 safety: tutors should be cleared before teaching minors.
   */
  backgroundCheckStatus?: ('none' | 'pending' | 'cleared' | 'failed' | 'expired') | null;
  backgroundCheckCompletedAt?: string | null;
  /**
   * Whether government-issued ID has been verified.
   */
  identityVerified?: boolean | null;
  /**
   * Government-issued ID for identity verification (admin-reviewed).
   */
  identityDocument?: (number | null) | Media;
  /**
   * Teaching certificates, degrees, or credentials.
   */
  teachingCertifications?:
    | {
        name: string;
        issuingBody?: string | null;
        issueDate?: string | null;
        expiryDate?: string | null;
        document?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Nigerian grade levels this tutor is qualified to teach.
   */
  gradesTaught?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )[]
    | null;
  /**
   * Average rating for this tutor (0-5).
   */
  rating?: number | null;
  /**
   * Total number of reviews received by this tutor.
   */
  totalReviews?: number | null;
  /**
   * Whether the tutor has completed the onboarding flow.
   */
  onboardingCompleted?: boolean | null;
  /**
   * A short headline or tagline for the tutor profile.
   */
  headline?: string | null;
  bio?: string | null;
  yearsOfExperience?: number | null;
  mode?: ('online' | 'hybrid') | null;
  /**
   * How the tutor plans to use TutorCourt.
   */
  usagePlan?: ('existing' | 'marketplace' | 'both') | null;
  /**
   * Subjects this tutor teaches.
   */
  subjects?: (number | Subject)[] | null;
  /**
   * Hourly rate in Naira.
   */
  hourlyRate?: number | null;
  /**
   * Recurring weekly time slots when this tutor is available.
   */
  weeklyAvailability?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * 24h HH:MM
         */
        startTime: string;
        /**
         * 24h HH:MM
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Types of classes standardly offered by this tutor.
   */
  type?: ('one-on-one' | 'group')[] | null;
  /**
   * Minimum age of students the tutor teaches (K-12 range).
   */
  minAge?: number | null;
  /**
   * Maximum age of students the tutor teaches (K-12 range).
   */
  maxAge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  review: string;
  rating: number;
  user: number | User;
  tutor: number | TutorProfile;
  /**
   * Class this review is about (when applicable).
   */
  class?: (number | null) | Class;
  /**
   * Booking this review is about (when applicable).
   */
  booking?: (number | null) | Booking;
  tutorResponse?: string | null;
  /**
   * Admin moderation flag. Only approved reviews are visible publicly.
   */
  isApproved?: boolean | null;
  /**
   * Set when a user reports this review for moderation.
   */
  flagged?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  tutor: number | User;
  title?: string | null;
  subject: number | Subject;
  description?: string | null;
  classType: 'one-on-one' | 'group';
  gradeLevel:
    | 'kindergarten'
    | 'grade_1'
    | 'grade_2'
    | 'grade_3'
    | 'grade_4'
    | 'grade_5'
    | 'grade_6'
    | 'grade_7'
    | 'grade_8'
    | 'grade_9'
    | 'grade_10'
    | 'grade_11'
    | 'grade_12'
    | 'others';
  /**
   * IANA timezone used to interpret schedule start/end times.
   */
  timezone: string;
  maxStudents?: number | null;
  startDate: string;
  endDate: string;
  schedule: {
    day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
    /**
     * 24-hour HH:MM format, interpreted in the class timezone.
     */
    startTime: string;
    /**
     * 24-hour HH:MM format, interpreted in the class timezone.
     */
    endTime: string;
    id?: string | null;
  }[];
  students?: (number | User)[] | null;
  parents?: (number | User)[] | null;
  status: 'scheduled' | 'active' | 'completed' | 'cancelled';
  whiteboard?: (number | null) | Whiteboard;
  /**
   * The marketplace booking this class was generated from (empty for tutor-created SaaS classes).
   */
  booking?: (number | null) | Booking;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards".
 */
export interface Whiteboard {
  id: number;
  title: string;
  owner: number | User;
  class?: (number | null) | Class;
  liveSession?: (number | null) | LiveSession;
  /**
   * Auto-generated on create. Used for public/share-link access.
   */
  shareToken?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-sessions".
 */
export interface LiveSession {
  id: number;
  class: number | Class;
  tutor: number | User;
  roomId: string;
  scheduledFor?: string | null;
  startedAt?: string | null;
  endedAt?: string | null;
  status: 'scheduled' | 'waiting' | 'live' | 'ended' | 'cancelled';
  /**
   * Deprecated: prefer live-session-participants for per-user join/leave records. Kept for backwards compatibility.
   */
  attendees?: (number | User)[] | null;
  showWhiteboard?: boolean | null;
  activeWhiteboard?: (number | null) | Whiteboard;
  /**
   * When enabled, enrolled students may draw on the shared whiteboard (not just the tutor).
   */
  whiteboardWritable?: boolean | null;
  coinsConsumed?: number | null;
  durationMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  tutor: number | TutorProfile;
  student: number | User;
  /**
   * Parent user when the booking is made on behalf of a managed student.
   */
  parent?: (number | null) | User;
  status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'refunded';
  paymentStatus: 'unpaid' | 'held' | 'paid' | 'refunded' | 'failed';
  /**
   * Linked transaction that paid for this booking.
   */
  transaction?: (number | null) | Transaction;
  /**
   * The class materialized from this booking once it is paid (held).
   */
  class?: (number | null) | Class;
  /**
   * Start date of the engagement
   */
  date: string;
  /**
   * End date of the engagement
   */
  endDate: string;
  hoursPerDay: number;
  daysOfWeek: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  subjects: (number | Subject)[];
  /**
   * Student's Nigerian grade level at time of booking.
   */
  gradeLevel?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )
    | null;
  /**
   * Total price for this booking
   */
  price: number;
  currency: 'ngn' | 'usd';
  /**
   * Message from the student to the tutor
   */
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Internal or gateway reference (e.g. Paystack reference). Unique.
   */
  reference?: string | null;
  gateway: 'wallet' | 'paystack' | 'manual';
  type: 'deposit' | 'payment' | 'refund' | 'payout' | 'credit_grant' | 'adjustment';
  sender: number | User;
  receiver: number | User;
  tutor?: (number | null) | User;
  relatedBooking?: (number | null) | Booking;
  relatedLiveSession?: (number | null) | LiveSession;
  /**
   * Amount in the smallest non-decimal unit (e.g. kobo or cents).
   */
  amount: number;
  currency: 'ngn' | 'usd';
  status: 'pending' | 'success' | 'failed' | 'reversed';
  description?: string | null;
  /**
   * Gateway response payload, idempotency keys, etc.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: number;
  user: number | User;
  currency: 'ngn' | 'usd';
  /**
   * Spendable balance in NGN/USD.
   */
  balance: number;
  /**
   * Funds reserved for in-flight bookings/escrow. Available balance is (balance - lockedBalance).
   */
  lockedBalance: number;
  /**
   * Tutoring credits used to pay for live-session minutes.
   */
  creditBalance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-requests".
 */
export interface PayoutRequest {
  id: number;
  tutor: number | User;
  amount: number;
  currency: 'ngn' | 'usd';
  bankName?: string | null;
  accountNumber?: string | null;
  accountName?: string | null;
  status: 'requested' | 'paid' | 'rejected';
  transaction?: (number | null) | Transaction;
  adminNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  user: number | User;
  parent: number | User;
  firstName: string;
  lastName: string;
  generatedEmail: string;
  /**
   * Plaintext for parent hand-off only. Read access restricted to owning parent / admin. Plan: replace with one-time reveal + reset flow.
   */
  generatedPassword: string;
  gradeLevel?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-invitations".
 */
export interface ClassInvitation {
  id: number;
  class: number | Class;
  inviter: number | User;
  inviteeEmail: string;
  inviteeType: 'parent' | 'student';
  token: string;
  status: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';
  acceptedBy?: (number | null) | User;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboard-slides".
 */
export interface WhiteboardSlide {
  id: number;
  whiteboard: number | Whiteboard;
  order: number;
  title?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aggregated attendance record per (liveSession, student). LiveSessionParticipants holds raw join/leave events; this collection is the rolled-up summary used for parent/tutor reports.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: number;
  liveSession: number | LiveSession;
  class: number | Class;
  student: number | User;
  parent?: (number | null) | User;
  tutor?: (number | null) | User;
  joinedAt: string;
  leftAt?: string | null;
  durationMinutes?: number | null;
  status: 'present' | 'late' | 'left-early' | 'absent';
  /**
   * How many minutes after the session started the student joined. Computed at join time from live-session.startedAt.
   */
  latenessMinutes?: number | null;
  /**
   * Auto-derived from durationMinutes vs session length when the session ends. good ≥ 80%, partial ≥ 40%, poor < 40%.
   */
  engagementFlag?: ('unknown' | 'good' | 'partial' | 'poor' | 'absent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-user join/leave records for a live session. Use this collection (not LiveSessions.attendees) as the source of truth for who attended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-participants".
 */
export interface LiveSessionParticipant {
  id: number;
  liveSession: number | LiveSession;
  class: number | Class;
  user: number | User;
  accountType: 'tutor' | 'student' | 'parent';
  joinedAt: string;
  leftAt?: string | null;
  durationSeconds?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chat messages posted during a live class session.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-messages".
 */
export interface LiveSessionMessage {
  id: number;
  liveSession: number | LiveSession;
  sender: number | User;
  senderName: string;
  senderAccountType?: ('tutor' | 'student' | 'parent' | 'admin') | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments".
 */
export interface Assessment {
  id: number;
  title: string;
  description?: string | null;
  subject: number | Subject;
  tutor: number | User;
  type: 'quiz' | 'flashcard' | 'practice_test' | 'homework';
  /**
   * Target Nigerian grade level for this assessment.
   */
  gradeLevel?:
    | (
        | 'kindergarten'
        | 'grade_1'
        | 'grade_2'
        | 'grade_3'
        | 'grade_4'
        | 'grade_5'
        | 'grade_6'
        | 'grade_7'
        | 'grade_8'
        | 'grade_9'
        | 'grade_10'
        | 'grade_11'
        | 'grade_12'
        | 'others'
      )
    | null;
  /**
   * Instructions shown to the student before they begin.
   */
  instructions?: string | null;
  /**
   * Optional time limit in minutes (0 = no limit, max 600).
   */
  timeLimitMinutes?: number | null;
  /**
   * Max questions to include (cap of 200).
   */
  maxQuestions?: number | null;
  /**
   * Passing score percentage (0-100).
   */
  passingScore?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-questions".
 */
export interface AssessmentQuestion {
  id: number;
  assessment: number | Assessment;
  /**
   * Supports Markdown syntax
   */
  questionText: string;
  type: 'single_choice' | 'multiple_choice' | 'true_false' | 'short_answer' | 'essay';
  /**
   * Optional image to accompany the question (useful for younger grades).
   */
  image?: (number | null) | Media;
  /**
   * For choice-based questions. Mark one or more as correct.
   */
  options?:
    | {
        optionText: string;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown after the student answers (optional)
   */
  explanation?: string | null;
  points: number;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-assessments".
 */
export interface TutorAssessment {
  id: number;
  assessment: number | Assessment;
  tutor: number | User;
  student: number | User;
  class: number | Class;
  selectedQuestions?: (number | AssessmentQuestion)[] | null;
  status: 'pending' | 'in_progress' | 'completed' | 'expired';
  dueDate?: string | null;
  /**
   * How many times the student may submit (1 = single attempt).
   */
  maxAttempts?: number | null;
  /**
   * Number of submissions made so far. Updated server-side.
   */
  attemptCount?: number | null;
  instructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-results".
 */
export interface AssessmentResult {
  id: number;
  tutorAssessment: number | TutorAssessment;
  student: number | User;
  tutor: number | User;
  answers?:
    | {
        question: number | AssessmentQuestion;
        selectedOptions?:
          | {
              optionIndex?: number | null;
              id?: string | null;
            }[]
          | null;
        textAnswer?: string | null;
        isCorrect?: boolean | null;
        pointsEarned?: number | null;
        id?: string | null;
      }[]
    | null;
  totalPoints?: number | null;
  earnedPoints?: number | null;
  /**
   * Score as a percentage (0-100)
   */
  score?: number | null;
  passed?: boolean | null;
  /**
   * Which attempt this result represents (1-based).
   */
  attempt?: number | null;
  /**
   * Once set, the student can no longer edit answers.
   */
  submittedAt?: string | null;
  timeTakenSeconds?: number | null;
  /**
   * Optional tutor feedback on the result
   */
  feedback?: string | null;
  /**
   * True when the result contains short-answer/essay questions that still need to be graded by the tutor.
   */
  pendingManualGrading?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  /**
   * User that triggered this notification (optional).
   */
  actor?: (number | null) | User;
  type:
    | 'student_joined_class'
    | 'parent_accepted_invite'
    | 'student_added_to_class'
    | 'assessment_completed'
    | 'assessment_sent'
    | 'new_booking'
    | 'class_reminder'
    | 'payment_received'
    | 'general';
  title: string;
  message: string;
  isRead?: boolean | null;
  /**
   * When the notification was surfaced/viewed (badge cleared). Distinct from isRead which is set when opened.
   */
  seenAt?: string | null;
  priority?: ('low' | 'normal' | 'high') | null;
  /**
   * Optional URL to redirect to when notification is clicked
   */
  link?: string | null;
  relatedEntity?: {
    collection?: string | null;
    id?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-user activity feed. Subject is the user whose timeline this row belongs to; actor is who triggered it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: number;
  /**
   * Whose activity feed this row belongs to. A parent reading a child sees rows where subject = child.
   */
  subject: number | User;
  /**
   * User who triggered the event (may equal subject).
   */
  actor?: (number | null) | User;
  type: 'assessment_assigned' | 'assessment_completed' | 'class_joined' | 'class_left' | 'class_ended';
  title: string;
  description?: string | null;
  /**
   * In-app deep-link the activity row should navigate to.
   */
  link?: string | null;
  relatedCollection?: string | null;
  relatedId?: string | null;
  /**
   * Arbitrary structured payload — score, duration, etc.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tutor-profiles';
        value: number | TutorProfile;
      } | null)
    | ({
        relationTo: 'subjects';
        value: number | Subject;
      } | null)
    | ({
        relationTo: 'subject-categories';
        value: number | SubjectCategory;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'wallets';
        value: number | Wallet;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'payout-requests';
        value: number | PayoutRequest;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'class-invitations';
        value: number | ClassInvitation;
      } | null)
    | ({
        relationTo: 'whiteboards';
        value: number | Whiteboard;
      } | null)
    | ({
        relationTo: 'whiteboard-slides';
        value: number | WhiteboardSlide;
      } | null)
    | ({
        relationTo: 'live-sessions';
        value: number | LiveSession;
      } | null)
    | ({
        relationTo: 'attendance';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'live-session-participants';
        value: number | LiveSessionParticipant;
      } | null)
    | ({
        relationTo: 'live-session-messages';
        value: number | LiveSessionMessage;
      } | null)
    | ({
        relationTo: 'assessments';
        value: number | Assessment;
      } | null)
    | ({
        relationTo: 'assessment-questions';
        value: number | AssessmentQuestion;
      } | null)
    | ({
        relationTo: 'tutor-assessments';
        value: number | TutorAssessment;
      } | null)
    | ({
        relationTo: 'assessment-results';
        value: number | AssessmentResult;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'activity-logs';
        value: number | ActivityLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  accountType?: T;
  phoneNumber?: T;
  country?: T;
  timezone?: T;
  avatar?: T;
  dateOfBirth?: T;
  isActive?: T;
  parent?: T;
  isManagedAccount?: T;
  parentalConsentGiven?: T;
  hasCompletedOnboarding?: T;
  subjectsOfInterest?: T;
  gradeLevel?: T;
  learningGoals?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  purpose?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-profiles_select".
 */
export interface TutorProfilesSelect<T extends boolean = true> {
  slug?: T;
  user?: T;
  isApproved?: T;
  backgroundCheckStatus?: T;
  backgroundCheckCompletedAt?: T;
  identityVerified?: T;
  identityDocument?: T;
  teachingCertifications?:
    | T
    | {
        name?: T;
        issuingBody?: T;
        issueDate?: T;
        expiryDate?: T;
        document?: T;
        id?: T;
      };
  gradesTaught?: T;
  rating?: T;
  totalReviews?: T;
  onboardingCompleted?: T;
  headline?: T;
  bio?: T;
  yearsOfExperience?: T;
  mode?: T;
  usagePlan?: T;
  subjects?: T;
  hourlyRate?: T;
  weeklyAvailability?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  type?: T;
  minAge?: T;
  maxAge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  gradeLevels?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-categories_select".
 */
export interface SubjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  review?: T;
  rating?: T;
  user?: T;
  tutor?: T;
  class?: T;
  booking?: T;
  tutorResponse?: T;
  isApproved?: T;
  flagged?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  user?: T;
  currency?: T;
  balance?: T;
  lockedBalance?: T;
  creditBalance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  reference?: T;
  gateway?: T;
  type?: T;
  sender?: T;
  receiver?: T;
  tutor?: T;
  relatedBooking?: T;
  relatedLiveSession?: T;
  amount?: T;
  currency?: T;
  status?: T;
  description?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-requests_select".
 */
export interface PayoutRequestsSelect<T extends boolean = true> {
  tutor?: T;
  amount?: T;
  currency?: T;
  bankName?: T;
  accountNumber?: T;
  accountName?: T;
  status?: T;
  transaction?: T;
  adminNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  tutor?: T;
  student?: T;
  parent?: T;
  status?: T;
  paymentStatus?: T;
  transaction?: T;
  class?: T;
  date?: T;
  endDate?: T;
  hoursPerDay?: T;
  daysOfWeek?: T;
  subjects?: T;
  gradeLevel?: T;
  price?: T;
  currency?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  user?: T;
  parent?: T;
  firstName?: T;
  lastName?: T;
  generatedEmail?: T;
  generatedPassword?: T;
  gradeLevel?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  tutor?: T;
  title?: T;
  subject?: T;
  description?: T;
  classType?: T;
  gradeLevel?: T;
  timezone?: T;
  maxStudents?: T;
  startDate?: T;
  endDate?: T;
  schedule?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  students?: T;
  parents?: T;
  status?: T;
  whiteboard?: T;
  booking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-invitations_select".
 */
export interface ClassInvitationsSelect<T extends boolean = true> {
  class?: T;
  inviter?: T;
  inviteeEmail?: T;
  inviteeType?: T;
  token?: T;
  status?: T;
  acceptedBy?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards_select".
 */
export interface WhiteboardsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  class?: T;
  liveSession?: T;
  shareToken?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboard-slides_select".
 */
export interface WhiteboardSlidesSelect<T extends boolean = true> {
  whiteboard?: T;
  order?: T;
  title?: T;
  data?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-sessions_select".
 */
export interface LiveSessionsSelect<T extends boolean = true> {
  class?: T;
  tutor?: T;
  roomId?: T;
  scheduledFor?: T;
  startedAt?: T;
  endedAt?: T;
  status?: T;
  attendees?: T;
  showWhiteboard?: T;
  activeWhiteboard?: T;
  whiteboardWritable?: T;
  coinsConsumed?: T;
  durationMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  liveSession?: T;
  class?: T;
  student?: T;
  parent?: T;
  tutor?: T;
  joinedAt?: T;
  leftAt?: T;
  durationMinutes?: T;
  status?: T;
  latenessMinutes?: T;
  engagementFlag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-participants_select".
 */
export interface LiveSessionParticipantsSelect<T extends boolean = true> {
  liveSession?: T;
  class?: T;
  user?: T;
  accountType?: T;
  joinedAt?: T;
  leftAt?: T;
  durationSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-session-messages_select".
 */
export interface LiveSessionMessagesSelect<T extends boolean = true> {
  liveSession?: T;
  sender?: T;
  senderName?: T;
  senderAccountType?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments_select".
 */
export interface AssessmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  subject?: T;
  tutor?: T;
  type?: T;
  gradeLevel?: T;
  instructions?: T;
  timeLimitMinutes?: T;
  maxQuestions?: T;
  passingScore?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-questions_select".
 */
export interface AssessmentQuestionsSelect<T extends boolean = true> {
  assessment?: T;
  questionText?: T;
  type?: T;
  image?: T;
  options?:
    | T
    | {
        optionText?: T;
        isCorrect?: T;
        id?: T;
      };
  explanation?: T;
  points?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutor-assessments_select".
 */
export interface TutorAssessmentsSelect<T extends boolean = true> {
  assessment?: T;
  tutor?: T;
  student?: T;
  class?: T;
  selectedQuestions?: T;
  status?: T;
  dueDate?: T;
  maxAttempts?: T;
  attemptCount?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessment-results_select".
 */
export interface AssessmentResultsSelect<T extends boolean = true> {
  tutorAssessment?: T;
  student?: T;
  tutor?: T;
  answers?:
    | T
    | {
        question?: T;
        selectedOptions?:
          | T
          | {
              optionIndex?: T;
              id?: T;
            };
        textAnswer?: T;
        isCorrect?: T;
        pointsEarned?: T;
        id?: T;
      };
  totalPoints?: T;
  earnedPoints?: T;
  score?: T;
  passed?: T;
  attempt?: T;
  submittedAt?: T;
  timeTakenSeconds?: T;
  feedback?: T;
  pendingManualGrading?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  actor?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  seenAt?: T;
  priority?: T;
  link?: T;
  relatedEntity?:
    | T
    | {
        collection?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  subject?: T;
  actor?: T;
  type?: T;
  title?: T;
  description?: T;
  link?: T;
  relatedCollection?: T;
  relatedId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}